package sweetcupcakeshop.view;

import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import sweetcupcakeshop.model.*;
import sweetcupcakeshop.util.FileHandler;

public class LoginForm extends javax.swing.JFrame {

    // Define Standard Colors
    private static final Color BTN_BLUE = new Color(0, 102, 204);
    private static final Color BTN_RED  = new Color(204, 0, 51);
    private static final Color WHITE    = Color.WHITE;

    public LoginForm() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        lblIcon = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblSubtitle = new javax.swing.JLabel();
        formPanel = new javax.swing.JPanel();
        lblWelcome = new javax.swing.JLabel();
        separator = new javax.swing.JSeparator();
        lblUsername = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        lblStatus = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        lblFooter = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("The Sweet Cupcake Shop - Login");
        setResizable(false);
        getContentPane().setLayout(null);

        mainPanel.setBackground(new java.awt.Color(255, 248, 250));
        mainPanel.setLayout(null);

        headerPanel.setBackground(new java.awt.Color(75, 36, 55));
        headerPanel.setLayout(null);

        lblIcon.setFont(new java.awt.Font("Segoe UI Emoji", 0, 50)); // NOI18N
        lblIcon.setForeground(new java.awt.Color(255, 255, 255));
        lblIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIcon.setText("🧁");
        headerPanel.add(lblIcon);
        lblIcon.setBounds(0, 15, 480, 60);

        lblTitle.setFont(new java.awt.Font("Georgia", 1, 20)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("The Sweet Cupcake Shop");
        headerPanel.add(lblTitle);
        lblTitle.setBounds(20, 80, 440, 35);

        lblSubtitle.setFont(new java.awt.Font("Georgia", 2, 13)); // NOI18N
        lblSubtitle.setForeground(new java.awt.Color(255, 200, 215));
        lblSubtitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSubtitle.setText("Staff Management System");
        headerPanel.add(lblSubtitle);
        lblSubtitle.setBounds(20, 118, 440, 25);

        mainPanel.add(headerPanel);
        headerPanel.setBounds(0, 0, 480, 180);

        formPanel.setBackground(new java.awt.Color(255, 255, 255));
        formPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 210, 220)));
        formPanel.setLayout(null);

        lblWelcome.setFont(new java.awt.Font("Georgia", 1, 17)); // NOI18N
        lblWelcome.setForeground(new java.awt.Color(75, 36, 55));
        lblWelcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWelcome.setText("Welcome Back!");
        formPanel.add(lblWelcome);
        lblWelcome.setBounds(0, 15, 380, 30);

        separator.setForeground(new java.awt.Color(220, 200, 210));
        formPanel.add(separator);
        separator.setBounds(30, 50, 320, 10);

        lblUsername.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(50, 30, 40));
        lblUsername.setText("Username");
        formPanel.add(lblUsername);
        lblUsername.setBounds(30, 65, 100, 20);

        txtUsername.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        formPanel.add(txtUsername);
        txtUsername.setBounds(30, 88, 320, 38);

        lblPassword.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(50, 30, 40));
        lblPassword.setText("Password");
        formPanel.add(lblPassword);
        lblPassword.setBounds(30, 138, 100, 20);

        txtPassword.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        txtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPasswordKeyPressed(evt);
            }
        });
        formPanel.add(txtPassword);
        txtPassword.setBounds(30, 161, 320, 38);

        lblStatus.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        lblStatus.setForeground(new java.awt.Color(200, 50, 70));
        lblStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStatus.setText(" ");
        formPanel.add(lblStatus);
        lblStatus.setBounds(0, 204, 380, 20);

        // --- BLUE LOGIN BUTTON ---
        btnLogin.setBackground(BTN_BLUE);
        btnLogin.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnLogin.setForeground(WHITE);
        btnLogin.setText("LOGIN");
        btnLogin.setFocusPainted(false);
        btnLogin.setOpaque(true);
        btnLogin.setBorderPainted(false);
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        formPanel.add(btnLogin);
        btnLogin.setBounds(30, 228, 200, 42);

        // --- RED CLEAR BUTTON ---
        btnClear.setBackground(BTN_RED);
        btnClear.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnClear.setForeground(WHITE);
        btnClear.setText("CLEAR");
        btnClear.setFocusPainted(false);
        btnClear.setOpaque(true);
        btnClear.setBorderPainted(false);
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        formPanel.add(btnClear);
        btnClear.setBounds(240, 228, 110, 42);

        mainPanel.add(formPanel);
        formPanel.setBounds(50, 200, 380, 310);

        lblFooter.setFont(new java.awt.Font("Arial", 2, 10)); // NOI18N
        lblFooter.setForeground(new java.awt.Color(180, 140, 155));
        lblFooter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFooter.setText("Default: manager / manager123   |   cashier / cashier123");
        mainPanel.add(lblFooter);
        lblFooter.setBounds(0, 530, 480, 20);

        getContentPane().add(mainPanel);
        mainPanel.setBounds(0, 0, 480, 580);

        setSize(new java.awt.Dimension(496, 619));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {                                         
        String username = txtUsername.getText().trim();
        String password = new String(txtPassword.getPassword()).trim();

        if (username.isEmpty() || password.isEmpty()) {
            lblStatus.setText("Please enter username and password!");
            return;
        }

        User loggedInUser = FileHandler.authenticate(username, password);

        if (loggedInUser != null) {
            lblStatus.setForeground(new Color(0, 150, 0));
            lblStatus.setText("Success!");
            
            if (loggedInUser instanceof Manager) {
                new ManagerDashboard((Manager) loggedInUser).setVisible(true);
            } else {
                new CashierDashboard(loggedInUser).setVisible(true);
            }
            this.dispose();
        } else {
            lblStatus.setForeground(new Color(200, 50, 70));
            lblStatus.setText("Invalid credentials!");
            txtPassword.setText("");
        }
    }                                        

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {                                         
        txtUsername.setText("");
        txtPassword.setText("");
        lblStatus.setText(" ");
        txtUsername.requestFocus();
    }                                        

    private void txtPasswordKeyPressed(java.awt.event.KeyEvent evt) {                                       
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            btnLoginActionPerformed(null);
        }
    }                                      

    public static void main(String args[]) {
        // Force Metal LookAndFeel to ensure colors work across all platforms
        try {
            UIManager.setLookAndFeel(new javax.swing.plaf.metal.MetalLookAndFeel());
        } catch (Exception ex) {}

        FileHandler.initializeData();

        java.awt.EventQueue.invokeLater(() -> new LoginForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnLogin;
    private javax.swing.JPanel formPanel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel lblFooter;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblSubtitle;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JSeparator separator;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}