package sweetcupcakeshop.view;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import sweetcupcakeshop.model.*;
import sweetcupcakeshop.util.FileHandler;

public class ManagerUsersPanel extends javax.swing.JPanel {
    
    private Manager currentUser;
    private static final String[] USER_COLS = {"Username", "Full Name", "Role"};

    public ManagerUsersPanel(Manager manager) {
        this.currentUser = manager;
        initComponents();
        loadUserTable();
        
        // Style Table Header - Custom code after init
        if (tableUsers.getTableHeader() != null) {
            tableUsers.getTableHeader().setBackground(new Color(95, 50, 75));
            tableUsers.getTableHeader().setForeground(Color.WHITE);
            tableUsers.getTableHeader().setFont(new Font("Arial", Font.BOLD, 12));
        }
    }
    
    private void loadUserTable() {
        DefaultTableModel model = new DefaultTableModel(FileHandler.getUsersTableData(), USER_COLS) {
            @Override public boolean isCellEditable(int r, int c) { return false; }
        };
        tableUsers.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        userCard = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtNewUsername = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNewFullName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNewPassword = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        txtConfirmPassword = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        lblUserStatus = new javax.swing.JLabel();
        btnCreateUser = new javax.swing.JButton();
        btnClearUserForm = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableUsers = new javax.swing.JTable();

        setBackground(new java.awt.Color(250, 245, 248));
        setPreferredSize(new java.awt.Dimension(880, 600));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(75, 36, 55));
        jLabel1.setText("Create New Cashier Account");
        add(jLabel1);
        jLabel1.setBounds(0, 0, 233, 19);

        userCard.setBackground(new java.awt.Color(255, 255, 255));
        userCard.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 190, 205)));
        userCard.setLayout(null);

        jLabel2.setText("Username *");
        userCard.add(jLabel2);
        userCard.add(txtNewUsername);

        jLabel3.setText("Full Name *");
        userCard.add(jLabel3);
        userCard.add(txtNewFullName);

        jLabel4.setText("Password *");
        userCard.add(jLabel4);
        userCard.add(txtNewPassword);

        jLabel5.setText("Confirm Password *");
        userCard.add(jLabel5);
        userCard.add(txtConfirmPassword);

        jLabel6.setFont(new java.awt.Font("Arial", 2, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(150, 100, 130));
        jLabel6.setText("Role: CASHIER (Managers can only create Cashier accounts)");
        userCard.add(jLabel6);

        lblUserStatus.setText(" ");
        userCard.add(lblUserStatus);

        add(userCard);
        userCard.setBounds(0, 0, 0, 0);

        btnCreateUser.setBackground(new java.awt.Color(75, 36, 55));
        btnCreateUser.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnCreateUser.setForeground(new java.awt.Color(255, 255, 255));
        btnCreateUser.setText("Create Account");
        btnCreateUser.addActionListener(this::btnCreateUserActionPerformed);
        add(btnCreateUser);
        btnCreateUser.setBounds(0, 0, 138, 24);

        btnClearUserForm.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnClearUserForm.setForeground(new java.awt.Color(75, 36, 55));
        btnClearUserForm.setText("Clear Form");
        btnClearUserForm.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(75, 36, 55), 2));
        btnClearUserForm.addActionListener(this::btnClearUserFormActionPerformed);
        add(btnClearUserForm);
        btnClearUserForm.setBounds(0, 0, 81, 21);

        jLabel7.setFont(new java.awt.Font("Georgia", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(75, 36, 55));
        jLabel7.setText("Existing Users");
        add(jLabel7);
        jLabel7.setBounds(0, 0, 118, 19);

        tableUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tableUsers.setRowHeight(28);
        jScrollPane1.setViewportView(tableUsers);

        add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 930, 520);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateUserActionPerformed
        String username = txtNewUsername.getText().trim();
        String fullName = txtNewFullName.getText().trim();
        String password = new String(txtNewPassword.getPassword()).trim();
        String confirmPwd = new String(txtConfirmPassword.getPassword()).trim();

        if (username.isEmpty() || fullName.isEmpty() || password.isEmpty() || confirmPwd.isEmpty()) {
            lblUserStatus.setText("Please fill in all required fields (*)");
            lblUserStatus.setForeground(Color.RED);
            return;
        }
        if (!password.equals(confirmPwd)) {
            lblUserStatus.setText("Passwords do not match.");
            lblUserStatus.setForeground(Color.RED);
            return;
        }
        
        // Polymorphism usage
        User newCashier = currentUser.createCashierAccount(username, password, fullName);
        if (FileHandler.addUser(newCashier)) {
            lblUserStatus.setText("Account created!");
            lblUserStatus.setForeground(new Color(0, 150, 0));
            btnClearUserFormActionPerformed(null);
            loadUserTable();
        } else {
            lblUserStatus.setText("Username already exists.");
            lblUserStatus.setForeground(Color.RED);
        }
    }//GEN-LAST:event_btnCreateUserActionPerformed

    private void btnClearUserFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearUserFormActionPerformed
        txtNewUsername.setText("");
        txtNewFullName.setText("");
        txtNewPassword.setText("");
        txtConfirmPassword.setText("");
        lblUserStatus.setText("");
    }//GEN-LAST:event_btnClearUserFormActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClearUserForm;
    private javax.swing.JButton btnCreateUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblUserStatus;
    private javax.swing.JTable tableUsers;
    private javax.swing.JPasswordField txtConfirmPassword;
    private javax.swing.JTextField txtNewFullName;
    private javax.swing.JPasswordField txtNewPassword;
    private javax.swing.JTextField txtNewUsername;
    private javax.swing.JPanel userCard;
    // End of variables declaration//GEN-END:variables
}